language: python
python:
  - "3.6.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - cd mobileapp
  - pytest # or py.test for Python versions 3.5 and below