language: python
python:
  - "3.6.8"

dist: bionic
services:
  - xvfb

install:
  - pip install pipenv
  - sudo apt-get install python3-pip
  - sudo apt-get install cython3 python3-dev
  - sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev
  - python -m pip install git+https://github.com/kivy/kivy.git@master
  - pipenv install

script:
  - cd mobileapp
  - xvfb-run -a pytest